language: generic
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - npm update -g npm
  - npm run build
branches:
  only:
    - master
env:
  global:
    secure: encrypted-github-token
